
use ass;
CREATE TABLE TheDD(
    maDD VARCHAR(10) PRIMARY KEY,
    trangThai NVARCHAR(15)
);
CREATE TABLE doanhThu(
    maDT VARCHAR(10) PRIMARY KEY,
    tongTien money,
    donDaTao int,
    ghiChu NVARCHAR(50)
);
CREATE TABLE LoaiDoUong(
    maLDU VARCHAR(10) PRIMARY KEY,
    ten NVARCHAR(10)
);  
CREATE TABLE DoUong(
    maDU VARCHAR(10) PRIMARY KEY,
    tenDU NVARCHAR(15),
    anhDoUong image,
    size VARCHAR(5),
    maLDU VARCHAR(10) FOREIGN KEY REFERENCES LoaiDoUong(maLDU)
);
CREATE TABLE ChiTietPhieuBan(
    ID int IDENTITY(1,1) PRIMARY KEY,
    maDU VARCHAR(10) FOREIGN KEY REFERENCES DoUong(maDU),
    gia money
);

CREATE TABLE NhanVien(
    maNV VARCHAR(10) PRIMARY KEY,
    hoVaTen NVARCHAR(30),
    Namsinh DATE,
    anh image,
    maDT VARCHAR(10) FOREIGN KEY REFERENCES doanhThu(maDT)
);
CREATE TABLE PhieuBanHang(
    maPhieu VARCHAR(10) PRIMARY KEY,
    ngayTao DATE,
    maDU VARCHAR(10) FOREIGN KEY REFERENCES DoUong(maDU),
    maDD VARCHAR(10) FOREIGN KEY REFERENCES TheDD(maDD),
    ghiChu NVARCHAR(20),
    maNV VARCHAR(10) FOREIGN KEY REFERENCES NhanVien(maNV)
);
CREATE TABLE NguoiDung(
    maND VARCHAR(10) PRIMARY KEY,
    tenND VARCHAR(15),
    matKhau VARCHAR(20),
    chucVu NVARCHAR(15),
    maNV VARCHAR(10) FOREIGN KEY REFERENCES NhanVien(maNV)
);
