/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.cafe.ui.manager;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import poly.cafe.controller.entityController.CaLamCTR;
import poly.cafe.dao.entityDAO.CaLamDAO;
import poly.cafe.dao.entityDAO.NhanVienDAO;
import poly.cafe.dao.impl.Calamimpl;
import poly.cafe.dao.impl.NhanVienimpl;
import poly.cafe.entity.CaLam;
import poly.cafe.entity.NhanVien;
import poly.cafe.util.XAuth;
import poly.cafe.util.XDialog;

/**
 *
 * @author baoha
 */
public class CaLamPanel extends javax.swing.JPanel implements CaLamCTR{
    CaLamDAO dao = new Calamimpl();
    List<CaLam> items = new ArrayList<>();
    NhanVienDAO nvDao = new NhanVienimpl();
    /**
     * Creates new form CaLamPanel
     */
    public CaLamPanel(boolean visible) {
        initComponents();
        fillToTable();
        setQuyen();
        setButtonVisible(visible);
        tblCaLam.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {{ setHorizontalAlignment(CENTER); }});

    }
    public void setButtonVisible(boolean visible) {
    jButton1.setVisible(visible);
}
    public void fillToTableTheoDieuKien() {
        try {
    Calamimpl dao = new Calamimpl();
    String keyword = txtFind.getText().trim();

    List<CaLam> list = dao.findByKeyword(keyword);

    DefaultTableModel model = (DefaultTableModel) tblCaLam.getModel();
    model.setRowCount(0);

    if (list.isEmpty()) {
        XDialog.alert("Không tìm thấy ca làm nào.");
        return;
    }

    for (CaLam item : list) {
        Object[] row = {
            item.getBuoi(),
            item.getMaNV(),
            item.getHoTen(),
            false
        };
        model.addRow(row);
    }

} catch (Exception e) {}

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCaLam = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdoCa1 = new javax.swing.JRadioButton();
        rdoCa2 = new javax.swing.JRadioButton();
        rdoCa3 = new javax.swing.JRadioButton();
        lblID = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtmaNV = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnADD = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnMoveLast = new javax.swing.JButton();
        btnMoveNext = new javax.swing.JButton();
        btnMovePrevious = new javax.swing.JButton();
        btnMoveFirst = new javax.swing.JButton();
        txtFind = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnfind = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1010, 320));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CA LÀM");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 1051, 36));

        tblCaLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Buổi", "Mã Nhân viên", "Họ tên"
            }
        ));
        tblCaLam.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblCaLamAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblCaLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCaLamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCaLam);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, 1080, 154));

        jLabel2.setText("ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 354, -1, -1));

        jLabel3.setText("Buổi:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 351, -1, -1));

        jLabel4.setText("Mã nhân viên:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 391, -1, -1));

        jLabel5.setText("Họ tên:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 438, 73, -1));

        buttonGroup1.add(rdoCa1);
        rdoCa1.setText("Sáng (7h-10h)");
        add(rdoCa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 349, -1, -1));

        buttonGroup1.add(rdoCa2);
        rdoCa2.setText("Chiều (15h-18h)");
        add(rdoCa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        buttonGroup1.add(rdoCa3);
        rdoCa3.setText("Tối (19h-22h)");
        add(rdoCa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        lblID.setText("1");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 351, -1, -1));
        add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 432, 334, -1));
        add(txtmaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 388, 334, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/clear.png"))); // NOI18N
        btnClear.setText("Làm mới");
        btnClear.setPreferredSize(new java.awt.Dimension(72, 7));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 113, 119, 27));

        btnADD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/insert.png"))); // NOI18N
        btnADD.setText("Thêm");
        btnADD.setPreferredSize(new java.awt.Dimension(72, 7));
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        add(btnADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 113, 119, 27));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/update.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.setPreferredSize(new java.awt.Dimension(72, 7));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 113, 119, 27));

        btnDel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/delete.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.setPreferredSize(new java.awt.Dimension(72, 7));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 113, 119, 27));

        btnRead.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/read.png"))); // NOI18N
        btnRead.setText("Đọc");
        btnRead.setPreferredSize(new java.awt.Dimension(72, 7));
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 113, 119, 27));

        btnMoveLast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMoveLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/cuoi.png"))); // NOI18N
        btnMoveLast.setText("Trang cuối");
        btnMoveLast.setPreferredSize(new java.awt.Dimension(72, 21));
        btnMoveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveLastActionPerformed(evt);
            }
        });
        add(btnMoveLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 130, 23));

        btnMoveNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMoveNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/tien.png"))); // NOI18N
        btnMoveNext.setText("Tiếp");
        btnMoveNext.setPreferredSize(new java.awt.Dimension(72, 21));
        btnMoveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveNextActionPerformed(evt);
            }
        });
        add(btnMoveNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 91, -1));

        btnMovePrevious.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMovePrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/lui.png"))); // NOI18N
        btnMovePrevious.setText("Trước");
        btnMovePrevious.setPreferredSize(new java.awt.Dimension(72, 21));
        btnMovePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePreviousActionPerformed(evt);
            }
        });
        add(btnMovePrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 100, -1));

        btnMoveFirst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMoveFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/dau.png"))); // NOI18N
        btnMoveFirst.setText("Trang đầu");
        btnMoveFirst.setPreferredSize(new java.awt.Dimension(72, 21));
        btnMoveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveFirstActionPerformed(evt);
            }
        });
        add(btnMoveFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 310, 130, -1));

        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });
        add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 232, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tìm kiếm:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        btnfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/find.png"))); // NOI18N
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });
        add(btnfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void tblCaLamAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblCaLamAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCaLamAncestorAdded

    private void tblCaLamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCaLamMouseClicked
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_tblCaLamMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
        XDialog.alert("Đã xóa toàn bộ nội dung");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        // TODO add your handling code here:
        if(checkAll()){
            create();
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(checkAll()){
            update();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        if(checkAll()){
            delete();
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        fillToTable();
        XDialog.alert("Đã load lại dữ liệu");
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnMoveLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveLastActionPerformed
        // TODO add your handling code here:
        moveLast();
    }//GEN-LAST:event_btnMoveLastActionPerformed

    private void btnMoveNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveNextActionPerformed
        // TODO add your handling code here:
        moveNext();
    }//GEN-LAST:event_btnMoveNextActionPerformed

    private void btnMovePreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovePreviousActionPerformed
        // TODO add your handling code here:
        movePrevious();
    }//GEN-LAST:event_btnMovePreviousActionPerformed

    private void btnMoveFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveFirstActionPerformed
        // TODO add your handling code here:
        moveFirst();
    }//GEN-LAST:event_btnMoveFirstActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
            fillToTableTheoDieuKien();
            moveFirst();

    }//GEN-LAST:event_btnfindActionPerformed

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnMoveFirst;
    private javax.swing.JButton btnMoveLast;
    private javax.swing.JButton btnMoveNext;
    private javax.swing.JButton btnMovePrevious;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnfind;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JRadioButton rdoCa1;
    private javax.swing.JRadioButton rdoCa2;
    private javax.swing.JRadioButton rdoCa3;
    private javax.swing.JTable tblCaLam;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtmaNV;
    // End of variables declaration//GEN-END:variables
    public void setQuyen() {
    if (XAuth.isViewer()) {
        // Phục vụ không được quyền gì
        btnADD.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDel.setEnabled(false);
        btnRead.setEnabled(true);
    } else if (XAuth.isStaff()) {
        // Nhân viên không được thêm/sửa/xóa nhân viên
        btnADD.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDel.setEnabled(false);
        btnRead.setEnabled(true);
    }else if (XAuth.isManager()) {
        // Nhân viên không được thêm/sửa/xóa nhân viên
        btnADD.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDel.setEnabled(true);
        btnRead.setEnabled(true);
    }
    // Quản lý thì không cần giới hạn
}
    @Override
    public void open() {
    }

    @Override
    public void setForm(CaLam entity) {
        txtmaNV.setText(entity.getMaNV());
        if (entity.getBuoi()== null) {
            // Không chọn gì
            rdoCa1.setSelected(false);
            rdoCa2.setSelected(false);
            rdoCa3.setSelected(false);
        } else {
            switch (entity.getBuoi()) {
                case "Sáng":
                    rdoCa1.setSelected(true);
                    break;
                case "Chiều":
                    rdoCa2.setSelected(true);
                    break;
                case "Tối":
                    rdoCa3.setSelected(true);
                    break;
                default:
                    // Không chọn radio button nào nếu giá trị lạ
                    rdoCa1.setSelected(false);
                    rdoCa2.setSelected(false);
                    rdoCa3.setSelected(false);
            }
        }
        txtHoTen.setText(entity.getHoTen());
        lblID.setText(String.valueOf(entity.getID()));
    }

    @Override
    public CaLam getForm() {
        CaLam entity = new CaLam();
        entity.setHoTen(txtHoTen.getText());
        if (rdoCa1.isSelected()) {
            entity.setBuoi("Sáng");
        } else if (rdoCa2.isSelected()) {
            entity.setBuoi("Chiều");
        } else if (rdoCa3.isSelected()) {
            entity.setBuoi("Tối");
        } else {
            entity.setBuoi(null);  // Không chọn chức vụ
        }
        entity.setMaNV(txtmaNV.getText());
        entity.setID(Integer.parseInt(lblID.getText()));
        return entity;
    }

    @Override
    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblCaLam.getModel();
        model.setRowCount(0);
        items = dao.findAll();
                items.forEach(item -> {
            Object[] rowData = {
                item.getBuoi(),
                item.getMaNV(),
                item.getHoTen(),
                false
            };
            model.addRow(rowData);
        });
    }
    @Override
    public void edit() {
        CaLam entity = items.get(tblCaLam.getSelectedRow());
        this.setForm(entity);
    }

    @Override
    public void create() {
        if (XDialog.confirm("Bạn thực sự muốn thêm nhân viên này?")) {
        CaLam entity = this.getForm();
        dao.create(entity);
        this.fillToTable();
        this.clear();
        XDialog.alert("Đã thêm thành công");
        }
    }

    @Override
    public void update() {
        if (XDialog.confirm("Bạn thực sự muốn thêm nhân viên này?")) {
        CaLam entity = this.getForm();
        dao.update(entity);
        this.fillToTable();
        this.clear();
        XDialog.alert("Đã cập nhật thành công");
    }
    }

    @Override
    public void delete() {
        if (XDialog.confirm("Bạn thực sự muốn xóa?")) {
         String id = txtmaNV.getText(); // "Ca1", "Ca2", hoặc "Ca3"
         dao.deleteById(id);
         this.fillToTable();
         this.clear();
         XDialog.alert("Đã xóa thành công");
     }
    }

    @Override
    public void clear() {
        this.setForm(new CaLam());
        this.setEditable(false);
    }

    @Override
    public void setEditable(boolean editable) {
       
    }


    @Override
    public boolean checkAll() {

    if (txtHoTen.getText()==null) {
        XDialog.alert( "Vui lòng nhập họ tên.");
        return false;
    }
    
    if(txtmaNV.getText()==null){
        XDialog.alert("Chưa nhập mã nhân viên");
        return false;
    }
    
    if (!rdoCa1.isSelected() && !rdoCa2.isSelected() && !rdoCa3.isSelected()) {
        XDialog.alert("Vui lòng chọn ca làm.");
        return false;
    }
    return true;
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        int currentIndex = tblCaLam.getSelectedRow();
        if (currentIndex == 0) {
            XDialog.alert( "Đã ở vị trí đầu tiên rồi!");
        } else {
            this.moveTo(0);
        }
    }

    @Override
    public void movePrevious() {
        this.moveTo(tblCaLam.getSelectedRow() - 1);
    }

    @Override
    public void moveNext() {
    this.moveTo(tblCaLam.getSelectedRow() + 1);
    }

    @Override
    public void moveLast() {
        this.moveTo(tblCaLam.getRowCount() - 1);
    }

    @Override
    public void moveTo(int index) {
         if (index < 0) {
        this.moveLast();
    } else if (index >= tblCaLam.getRowCount()) {
        this.moveFirst();
    } else {
        tblCaLam.clearSelection();
        tblCaLam.setRowSelectionInterval(index, index);
        this.edit();
    }
    }
}
