/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui.all;

import java.awt.Color;
import javax.swing.UIManager;
import poly.cafe.controller.entityController.Forgetpass;
import poly.cafe.dao.entityDAO.NhanVienDAO;
import poly.cafe.dao.impl.LoginandSignupimpl;
import poly.cafe.entity.NhanVien;
import poly.cafe.util.XAuth;
import poly.cafe.util.XDialog;
import poly.cafe.util.XEmail;

/**
 *
 * @author baoha
 */
public class ForgetPass extends javax.swing.JFrame implements Forgetpass{
    NhanVienDAO dao = new LoginandSignupimpl();
    private String generateOTP() {
    return String.valueOf(100000 + new java.util.Random().nextInt(900000));
}
    /**
     * Creates new form ForgetPass
     */
    public ForgetPass() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtOTP = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        btnLogin1 = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();
        btnSignup1 = new javax.swing.JButton();
        txtPassNew = new javax.swing.JPasswordField();
        chkNewPass1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        btnOTP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FORGET PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 750, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OTP:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        txtOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOTPActionPerformed(evt);
            }
        });
        getContentPane().add(txtOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 310, -1));
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 310, -1));

        btnLogin1.setText("Back");
        btnLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogin1MouseClicked(evt);
            }
        });
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        btnClose1.setText("Close");
        btnClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClose1MouseClicked(evt);
            }
        });
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        btnSignup1.setText("Done");
        btnSignup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup1MouseClicked(evt);
            }
        });
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 480, -1));
        getContentPane().add(txtPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 310, -1));

        chkNewPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNewPass1ActionPerformed(evt);
            }
        });
        getContentPane().add(chkNewPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NewPass:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        btnOTP.setText("Lấy mã OTP");
        btnOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOTPActionPerformed(evt);
            }
        });
        getContentPane().add(btnOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/Background_nht (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1MouseClicked

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        new PolyLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose1MouseClicked

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnSignup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup1MouseClicked

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        // TODO add your handling code here:
        setPass();
        dispose();
    }//GEN-LAST:event_btnSignup1ActionPerformed

    private void chkNewPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNewPass1ActionPerformed
        // TODO add your handling code here:
        if (chkNewPass1.isSelected()) {
            txtPassNew.setEchoChar((char) 0); // Hiện mật khẩu
        } else {
            txtPassNew.setEchoChar('●'); // Ẩn mật khẩu bằng dấu chấm
        }
    }//GEN-LAST:event_chkNewPass1ActionPerformed

    private void txtOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOTPActionPerformed

    private void btnOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOTPActionPerformed
        // TODO add your handling code here:
        createOTP();
    }//GEN-LAST:event_btnOTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new ForgetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnOTP;
    private javax.swing.JButton btnSignup1;
    private javax.swing.JCheckBox chkNewPass1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtOTP;
    private javax.swing.JPasswordField txtPassNew;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPass() {
        String username = txtUser.getText().trim();
        String passOld = new String(txtOTP.getPassword()).trim();
        String newPass = new String(txtPassNew.getPassword()).trim();
         
        if (!username.equals(XAuth.user.getMaNV())) {
            XDialog.alert("Sai tài khoản!");
        } else if (!passOld.equals(XAuth.user.getMatKhau())) {
            XDialog.alert("Sai mật khẩu cũ!");
        } else {
                XAuth.user.setMatKhau(newPass);
                dao.update(XAuth.user);
                XDialog.alert("Đổi mật khẩu thành công!");
                new PolyLogin().setVisible(true);
        }
    }
    public void createOTP(){
        String maNV = txtUser.getText().trim();
        String email=txtEmail.getText().trim();
        NhanVien nv  = dao.findById(maNV);
        
        if(nv ==null){
            XDialog.alert("Không tìm thấy mã nhân viên");
        }else if(!nv.getEmail().equals(email)){
            XDialog.alert("Sai email!");
            
        }else{
            String currentOTP = generateOTP();
            try {
                XEmail.sendOTP(email, currentOTP);
                XDialog.alert("Đã gửi mã OTP đến email của bạn!");
            } catch (Exception e) {
                e.printStackTrace();
                XDialog.alert("Gửi OTP thất bại: " + e.getMessage());
            }
        }
    }
    @Override
    public void open() {
        setLocationRelativeTo(null);
    }

    @Override
    public void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
